version: '3.7'

services:
  neo4j:
    image: latest
    container_name: "neo-gds"
    volumes:
      - $HOME/graph_data/nodes_svo_graph:/data
      - ./data:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/kgDemo
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - apoc.import.file.enabled=true
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4j_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_connector_bolt_thread__pool__max__size=1000
      - apoc.export.file.enabled=true
    networks:
      - odsc_net

networks:
  odsc_net:    

